### ISSUE TITLE
Add Dark and Light "Futuristic" Themes

### ISSUE THREAD

**Issue by GeorgeBerdovskiy** [PureChart/purechart#6]
## Background
While PureChart provides maximal flexibility when it comes to chart styling, we _do_ want to provide an abundance of default themes to choose from.

Following Ruby on Rails conventions, we've chosen to store chart styles in a specific folder. In the gem source code, they may be found under `lib/purechart/styles` as YML files. In a project using the gem, they must be inside of `app/purechart` and may be JSON, TOML, or YML / YAML files. Here's the default light theme as an example -

```yml
---
title:
  font: Inter Tight
  weight: 700
  color: "#000000"
labels:
  font: Inter Tight
  weight: 700
  color: "#000000"
ticks:
  font: Inter Tight
  weight: 400
  color: "#000000"
axes:
  style: "2px solid #000000"
gridlines:
  style: "2px dashed #00000033"
...
```

## Goal
Create a new theme called "futuristic" that uses a "futuristic" font like [Space Mono](https://fonts.google.com/specimen/Space+Mono?classification=Monospace) (although the choice is yours) and provides a palette of futuristic colors (whatever that means - you get to choose 😉).
- Use [this](https://docs.ansible.com/ansible/latest/reference_appendices/YAMLSyntax.html) page as a source on YAML syntax, including list definition
    - You'll need this because the colors should be defined as key, value pairs of names and hex values
- Visit [Google Fonts](https://fonts.google.com) for an excellent selection of free fonts!
- Visit [Flat UI Colors](https://flatuicolors.com) for a wide variety of great colors
